### PR TITLE
save channels to private data

### PR DESCRIPTION
**Pull request by earonesty**
save channels to private data and load at signin, so channel list doesn't change if you sign out/in

### CODE REVIEW

**Comment by reyamir** [comment]
I've found error, this function won't work, because in login screen, we not init relay yet
```js
export function useChannelManager() {
  const pool = useContext(RelayContext) as PoolWithChannels
  if (!pool.__channels) {
    pool.__channels = new ChannelManager(pool)
  }
  const mgr = pool.__channels
  return mgr
}
```

in `RelayProvider`, I make relay only init when ident has present
```js
const pool = useMemo(() => (ident ? new NostrPool(ident, db) : null), [privkey])
```

so in login screen, we not have ident (user not login) then relay will not work at this step

**Comment by reyamir** [comment]
I wonder that can we make `NostrPool` not require ident in first place `new NostrPool(ident, db)`, but can update ident it later, example: login/signup -> add indent to NostrPool

**Comment by earonesty** [comment]
yes thats fine.  a pool only needs relays unless you're posting messages

**Comment by earonesty** [comment]
please submit pr to arclib

**Pull request merged**
